version: '3.9'

networks:
  default:

volumes:
  redis:
  store:
  waku:
    name: 'waku-{{.Task.Slot}}'

services:
  caddy:
    image: ${CADDY_IMAGE}
    deploy:
      mode: replicated
    # Port mode must be mode: host to allow access to the external ip
    ports:
      - target: 80
        published: 80
        mode: ingress
      - target: 443
        published: 443
        mode: ingress
    volumes:
      - ./Caddyfile:/Caddyfile

  redis:
    image: 'redis:6-alpine'
    volumes:
      - redis:/data

  waku:
    image: ${WAKU_IMAGE}
    hostname: "waku.{{.Task.Slot}}"
    volumes:
      - waku:/key
    environment:
      SWARM_PEERS: "tasks.{{.Service.Name}}"
      STORE: "/ip4/138.197.189.151/tcp/60000/p2p/16Uiu2HAmF1iLV2KdC7YUj99YKoqCYWSiMBq34mdmQX28J8k4kqmn"

  relay:
    image: ${RELAY_IMAGE}
    environment:
      NODE_ENV: development
      REDIS_URL: "redis://redis:6379/{{.Task.Slot}}"
      WAKU_URL: "http://waku.{{.Task.Slot}}:8545"
