version: '3.9'

volumes:
  caddy_data:
  caddy_conf:

services:
  caddy:
    environment:
      DOMAIN: ${RELAY_URL:-localhost}
      EMAIL: ${CERTBOT_EMAIL}
      CLOUDFLARE_TOKEN: ${CLOUDFLARE_TOKEN}
      UPSTREAM_NAME: ${UPSTREAM_NAME:-relay}
      UPSTREAM_PORT: ${UPSTREAM_PORT:-5000}
      LOG_LEVEL: ERROR
    volumes:
      - ./stats.html:/www/index.html
    deploy:
      replicas: ${REPLICAS:-1}

  relay:
    image: ${RELAY_IMAGE}
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      RELAY_MODE: ${RELAY_MODE:-any}
    deploy:
      replicas: ${REPLICAS:-1}
  waku:
    deploy:
      replicas: ${REPLICAS:-1}
