version: '3.7'

services:
  nginx:
    environment:
      DOMAIN_URL: ${RELAY_URL}
      APP_ENV: ${NODE_ENV:-production}
      EMAIL: ${CERTBOT_EMAIL}
      CONTAINER_NAME: relay
      APP_PORT: 5000
      APP_QTY: 2
      CLOUDFLARE: ${CLOUDFLARE}
    depends_on:
      - relay

  relay0:
    image: ${RELAY_IMAGE}
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      REDIS_URL: redis://redis:6379/0
    deploy:
      resources:
        reservations:
          cpus: '0.6'
  relay1:
    image: ${RELAY_IMAGE}
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379/0
    deploy:
      resources:
        limits:
          memory: 2G
