# This workflow moves issues to the JavaScript board
# when they receive the "accepted" label
# When WalletConnect Org members create issues they
# are automatically "accepted".
# Else they need to manually receive that label during intake.
name: intake

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]

jobs:
  add-to-project:
    name: Add issue to board
    if: github.event.action == 'labeled' && github.event.label.name == 'accepted'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.0
        with:
          project-url: https://github.com/orgs/WalletConnect/projects/6
          github-token: ${{ secrets.ASSIGN_TO_PROJECT_GITHUB_TOKEN }}
          labeled: accepted
          label-operator: OR
  auto-promote:
    name: auto-promote
    if: github.event.action == 'opened' && github.event.sender.login != 'renovate[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Check Core Team membership
        uses: tspascoal/get-user-teams-membership@v3
        id: is-core-team
        with:
          username: ${{ github.event_name != 'pull_request' && github.event.issue.user.login || github.event.sender.login }}
          team: "Core Team"
          GITHUB_TOKEN: ${{ secrets.ASSIGN_TO_PROJECT_GITHUB_TOKEN }}
      - name: Print result
        env:
          CREATOR: ${{ github.event_name != 'pull_request' && github.event.issue.user.login || github.event.sender.login }}
          IS_TEAM_MEMBER: ${{ steps.is-core-team.outputs.isTeamMember }}
        run: echo "$CREATOR (Core Team Member $IS_TEAM_MEMBER) created this issue/PR"
      - name: Label issues
        if: ${{ steps.is-core-team.outputs.isTeamMember == 'true' }}
        uses: andymckay/labeler@3a4296e9dcdf9576b0456050db78cfd34853f260
        with:
          add-labels: "accepted"
          repo-token: ${{ secrets.ASSIGN_TO_PROJECT_GITHUB_TOKEN }}
