name: tests
on:
  push:

env:
  TERM: linux    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}               
      - name: build docker images
        run: |
          ## pull latest image to improve build time
          TAG=latest make pull
          make build-dev          
      - name: start server to run tests
        run: |
          make dev
      - name: run relay tests
        run: |
          make test-relay
      - name: run client tests
        run: |
          make test-client
